In [34]:
import numpy as op

In [38]:
li = op.array([[1,2,3,4,5] , [1,2,3,4,5]] )

In [40]:
li

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [39]:
li.shape

(2, 5)

In [33]:
li.dtype

dtype('int64')

In [41]:
li.size

10

In [42]:
l1 = op.arange(20)

In [44]:
l1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
lmod=l1.reshape(5,4)

In [48]:
l2=lmod.ravel()

In [49]:
l2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
l3=l2.reshape(5,4)

In [54]:
l4=l3.reshape(1,20)

In [59]:
x=op.array([1,2,3,4,5,6,7,8,9])

In [60]:
arr=x.reshape(3,3)

In [61]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr.sum(axis=0)

array([12, 15, 18])

In [63]:
arr.sum(axis=1)

array([ 6, 15, 24])